---
- name: Manage collectd.conf Configuration
  become: true
  template:
    src: "{{ role_path }}/templates/collectd.conf.j2"
    dest: "{{ collectd_config_file }}"
    owner: "{{ collectd_config_owner }}"
    group: "{{ collectd_config_group }}"
    mode: "{{ collectd_config_mode }}"
  notify:
    - Restart Collectd

- name: Create collectd.d directory
  become: true
  file:
    path: "{{ collectd_plugin_conf_dir }}"
    state: directory
    owner: "{{ collectd_config_owner }}"
    group: "{{ collectd_config_group }}"
    mode: "{{ collectd_plugin_conf_dir_mode }}"

- name: Include Collectd Plugins
  include: plugins.yml
  with_items: "{{ collectd_plugins }}"
  when: collectd_plugins | length > 0
  notify:
    - Restart Collectd

- name: Include Collectd Disable Plugins
  include: disable_plugins.yml
  with_items: "{{ collectd_disabled_plugins.values() }}"
  when: collectd_disabled_plugins | length > 0
  notify:
    - Restart Collectd

- name: Validate Collectd Configuration
  become: true
  command: "{{ collectd_cmd }} -t"
  changed_when: false

- name: Validate Collectd Plugins
  become: true
  command: "{{ collectd_cmd }} -T"
  changed_when: False
