---
- name: "Load Collectd {{ item.name }} plugin"
  become: true
  template:
    src: "{{ role_path }}/templates/plugins.conf.j2"
    dest: "{{ collectd_plugin_conf_dir }}/{{ item.order | default('10') }}_{{ item.name }}.conf"
    owner: "{{ collectd_config_owner }}"
    group: "{{ collectd_config_group }}"
    mode: "{{ collectd_plugin_conf_dir_mode }}"

- name: "Install Collectd {{ item.name }} Plugin Package"
  become: true
  package:
    name: "{{ item.package }}"
    state: present
  when:
    - (item.package is defined and item.package != "")
    - (ansible_os_family | lower == "redhat")
