---
- name: Collectd Testing Playbook
  hosts: all

  roles:
    - {role: ansible-role-collectd}

  tasks:
    - name: Install Collectd Disk Plugin
      include_role:
        name: ansible-role-collectd
        tasks_from: plugins_class.yml
      vars:
        collectd_plugins:
          - name: disk
            options:
              Disk:
                - '/^dm/'
                - '/^docker/'
              IgnoreSelected: true
              UdevNameAttr: DM_NAME
            package: collectd-disk
          - name: cpu
            options:
              ReportByState: true
              ReportByCpu: true
              ValuesPercentage: false
              ReportNumCpu: true
              ReportGuestState: false
              SubtractGuestState: true
          - name: postgresql
            options:
              Query magic:
                Statement: "SELECT magic FROM wizard WHERE host = $1;"
                Param: hostname
                Result:
                  Type: gauge
                  InstancePrefix: "magic"
                  ValuesFrom: magic
            package: collectd-postgresql
