---
- name: Import Collectd RPM GPG Key.
  become: true
  rpm_key:
    key: "{{ collectd_yum_repo_rpm_key }}"
    state: present
  when: ansible_distribution_major_version >= '6'

- name: Configure Collectd Yum repository.
  become: true
  yum_repository:
    name: collectd
    description: Collectd Yum Repo - $basearch
    baseurl: "{{ collectd_yum_repo_baseurl }}"
    enabled: "{{ collectd_yum_repo_enabled }}"
    gpgcheck: "{{ collectd_yum_repo_gpgcheck }}"
    gpgkey: "{{ collectd_yum_repo_rpm_key }}"
